events {
    worker_connections 1024;
}

http {
  upstream store_manager_nginx {
    least_conn;
    # VMs cibles ETS (le store_manager ecoute sur le port 5000 dans chaque VM)
    server 10.194.32.67:5000;
    server 10.194.32.68:5000;
  }

  server {
    listen 80;

    location / {
      proxy_pass http://store_manager_nginx;
    }
  }
}
